# Generated by Django 5.2 on 2025-04-03 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('address', models.CharField(max_length=75)),
                ('no_of_rooms', models.IntegerField()),
                ('occupied_rooms', models.IntegerField()),
            ],
        ),
    ]
