# Generated by Django 5.2 on 2025-04-03 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='no_of_rooms',
        ),
    ]
