# Generated by Django 5.2 on 2025-04-03 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_remove_hotel_no_of_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='number_of_rooms',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
