# Generated by Django 5.2 on 2025-04-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=75)),
                ('name', models.CharField(max_length=75)),
                ('department_number', models.CharField(max_length=75)),
            ],
        ),
    ]
