# Generated by Django 5.2 on 2025-04-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('bed_type', models.CharField(max_length=75)),
                ('rate', models.IntegerField()),
                ('smoking', models.BooleanField()),
                ('occupant_name', models.CharField()),
                ('is_occupied', models.BooleanField()),
            ],
        ),
    ]
